# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/project_2001659/cristian/somethingomthing/fastGPT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/project_2001659/cristian/somethingomthing/fastGPT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/project_2001659/cristian/somethingomthing/fastGPT/CMakeFiles /scratch/project_2001659/cristian/somethingomthing/fastGPT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/project_2001659/cristian/somethingomthing/fastGPT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fastgpt

# Build rule for target.
fastgpt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastgpt
.PHONY : fastgpt

# fast build rule for target.
fastgpt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/build
.PHONY : fastgpt/fast

#=============================================================================
# Target rules for targets named gpt2

# Build rule for target.
gpt2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpt2
.PHONY : gpt2

# fast build rule for target.
gpt2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpt2.dir/build.make CMakeFiles/gpt2.dir/build
.PHONY : gpt2/fast

#=============================================================================
# Target rules for targets named chat

# Build rule for target.
chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chat
.PHONY : chat

# fast build rule for target.
chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/build
.PHONY : chat/fast

#=============================================================================
# Target rules for targets named test_basic_input

# Build rule for target.
test_basic_input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_basic_input
.PHONY : test_basic_input

# fast build rule for target.
test_basic_input/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_basic_input.dir/build.make CMakeFiles/test_basic_input.dir/build
.PHONY : test_basic_input/fast

#=============================================================================
# Target rules for targets named test_more_inputs

# Build rule for target.
test_more_inputs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_more_inputs
.PHONY : test_more_inputs

# fast build rule for target.
test_more_inputs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_more_inputs.dir/build.make CMakeFiles/test_more_inputs.dir/build
.PHONY : test_more_inputs/fast

#=============================================================================
# Target rules for targets named test_chat

# Build rule for target.
test_chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_chat
.PHONY : test_chat

# fast build rule for target.
test_chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/build
.PHONY : test_chat/fast

chat.o: chat.f90.o
.PHONY : chat.o

# target to build an object file
chat.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.f90.o
.PHONY : chat.f90.o

chat.i: chat.f90.i
.PHONY : chat.i

# target to preprocess a source file
chat.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.f90.i
.PHONY : chat.f90.i

chat.s: chat.f90.s
.PHONY : chat.s

# target to generate assembly for a file
chat.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.f90.s
.PHONY : chat.f90.s

driver.o: driver.f90.o
.PHONY : driver.o

# target to build an object file
driver.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/driver.f90.o
.PHONY : driver.f90.o

driver.i: driver.f90.i
.PHONY : driver.i

# target to preprocess a source file
driver.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/driver.f90.i
.PHONY : driver.f90.i

driver.s: driver.f90.s
.PHONY : driver.s

# target to generate assembly for a file
driver.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/driver.f90.s
.PHONY : driver.f90.s

gpt2.o: gpt2.f90.o
.PHONY : gpt2.o

# target to build an object file
gpt2.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/gpt2.f90.o
.PHONY : gpt2.f90.o

gpt2.i: gpt2.f90.i
.PHONY : gpt2.i

# target to preprocess a source file
gpt2.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/gpt2.f90.i
.PHONY : gpt2.f90.i

gpt2.s: gpt2.f90.s
.PHONY : gpt2.s

# target to generate assembly for a file
gpt2.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/gpt2.f90.s
.PHONY : gpt2.f90.s

linalg_c.o: linalg_c.f90.o
.PHONY : linalg_c.o

# target to build an object file
linalg_c.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_c.f90.o
.PHONY : linalg_c.f90.o

linalg_c.i: linalg_c.f90.i
.PHONY : linalg_c.i

# target to preprocess a source file
linalg_c.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_c.f90.i
.PHONY : linalg_c.f90.i

linalg_c.s: linalg_c.f90.s
.PHONY : linalg_c.s

# target to generate assembly for a file
linalg_c.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_c.f90.s
.PHONY : linalg_c.f90.s

linalg_openblas.o: linalg_openblas.c.o
.PHONY : linalg_openblas.o

# target to build an object file
linalg_openblas.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_openblas.c.o
.PHONY : linalg_openblas.c.o

linalg_openblas.i: linalg_openblas.c.i
.PHONY : linalg_openblas.i

# target to preprocess a source file
linalg_openblas.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_openblas.c.i
.PHONY : linalg_openblas.c.i

linalg_openblas.s: linalg_openblas.c.s
.PHONY : linalg_openblas.s

# target to generate assembly for a file
linalg_openblas.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/linalg_openblas.c.s
.PHONY : linalg_openblas.c.s

main.o: main.f90.o
.PHONY : main.o

# target to build an object file
main.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpt2.dir/build.make CMakeFiles/gpt2.dir/main.f90.o
.PHONY : main.f90.o

main.i: main.f90.i
.PHONY : main.i

# target to preprocess a source file
main.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpt2.dir/build.make CMakeFiles/gpt2.dir/main.f90.i
.PHONY : main.f90.i

main.s: main.f90.s
.PHONY : main.s

# target to generate assembly for a file
main.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpt2.dir/build.make CMakeFiles/gpt2.dir/main.f90.s
.PHONY : main.f90.s

omp.o: omp.f90.o
.PHONY : omp.o

# target to build an object file
omp.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/omp.f90.o
.PHONY : omp.f90.o

omp.i: omp.f90.i
.PHONY : omp.i

# target to preprocess a source file
omp.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/omp.f90.i
.PHONY : omp.f90.i

omp.s: omp.f90.s
.PHONY : omp.s

# target to generate assembly for a file
omp.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/omp.f90.s
.PHONY : omp.f90.s

tests/test_basic_input.o: tests/test_basic_input.f90.o
.PHONY : tests/test_basic_input.o

# target to build an object file
tests/test_basic_input.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_basic_input.dir/build.make CMakeFiles/test_basic_input.dir/tests/test_basic_input.f90.o
.PHONY : tests/test_basic_input.f90.o

tests/test_basic_input.i: tests/test_basic_input.f90.i
.PHONY : tests/test_basic_input.i

# target to preprocess a source file
tests/test_basic_input.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_basic_input.dir/build.make CMakeFiles/test_basic_input.dir/tests/test_basic_input.f90.i
.PHONY : tests/test_basic_input.f90.i

tests/test_basic_input.s: tests/test_basic_input.f90.s
.PHONY : tests/test_basic_input.s

# target to generate assembly for a file
tests/test_basic_input.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_basic_input.dir/build.make CMakeFiles/test_basic_input.dir/tests/test_basic_input.f90.s
.PHONY : tests/test_basic_input.f90.s

tests/test_chat.o: tests/test_chat.f90.o
.PHONY : tests/test_chat.o

# target to build an object file
tests/test_chat.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/tests/test_chat.f90.o
.PHONY : tests/test_chat.f90.o

tests/test_chat.i: tests/test_chat.f90.i
.PHONY : tests/test_chat.i

# target to preprocess a source file
tests/test_chat.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/tests/test_chat.f90.i
.PHONY : tests/test_chat.f90.i

tests/test_chat.s: tests/test_chat.f90.s
.PHONY : tests/test_chat.s

# target to generate assembly for a file
tests/test_chat.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_chat.dir/build.make CMakeFiles/test_chat.dir/tests/test_chat.f90.s
.PHONY : tests/test_chat.f90.s

tests/test_more_inputs.o: tests/test_more_inputs.f90.o
.PHONY : tests/test_more_inputs.o

# target to build an object file
tests/test_more_inputs.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_more_inputs.dir/build.make CMakeFiles/test_more_inputs.dir/tests/test_more_inputs.f90.o
.PHONY : tests/test_more_inputs.f90.o

tests/test_more_inputs.i: tests/test_more_inputs.f90.i
.PHONY : tests/test_more_inputs.i

# target to preprocess a source file
tests/test_more_inputs.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_more_inputs.dir/build.make CMakeFiles/test_more_inputs.dir/tests/test_more_inputs.f90.i
.PHONY : tests/test_more_inputs.f90.i

tests/test_more_inputs.s: tests/test_more_inputs.f90.s
.PHONY : tests/test_more_inputs.s

# target to generate assembly for a file
tests/test_more_inputs.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_more_inputs.dir/build.make CMakeFiles/test_more_inputs.dir/tests/test_more_inputs.f90.s
.PHONY : tests/test_more_inputs.f90.s

tokenizer.o: tokenizer.f90.o
.PHONY : tokenizer.o

# target to build an object file
tokenizer.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/tokenizer.f90.o
.PHONY : tokenizer.f90.o

tokenizer.i: tokenizer.f90.i
.PHONY : tokenizer.i

# target to preprocess a source file
tokenizer.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/tokenizer.f90.i
.PHONY : tokenizer.f90.i

tokenizer.s: tokenizer.f90.s
.PHONY : tokenizer.s

# target to generate assembly for a file
tokenizer.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastgpt.dir/build.make CMakeFiles/fastgpt.dir/tokenizer.f90.s
.PHONY : tokenizer.f90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chat"
	@echo "... fastgpt"
	@echo "... gpt2"
	@echo "... test_basic_input"
	@echo "... test_chat"
	@echo "... test_more_inputs"
	@echo "... chat.o"
	@echo "... chat.i"
	@echo "... chat.s"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... gpt2.o"
	@echo "... gpt2.i"
	@echo "... gpt2.s"
	@echo "... linalg_c.o"
	@echo "... linalg_c.i"
	@echo "... linalg_c.s"
	@echo "... linalg_openblas.o"
	@echo "... linalg_openblas.i"
	@echo "... linalg_openblas.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... omp.o"
	@echo "... omp.i"
	@echo "... omp.s"
	@echo "... tests/test_basic_input.o"
	@echo "... tests/test_basic_input.i"
	@echo "... tests/test_basic_input.s"
	@echo "... tests/test_chat.o"
	@echo "... tests/test_chat.i"
	@echo "... tests/test_chat.s"
	@echo "... tests/test_more_inputs.o"
	@echo "... tests/test_more_inputs.i"
	@echo "... tests/test_more_inputs.s"
	@echo "... tokenizer.o"
	@echo "... tokenizer.i"
	@echo "... tokenizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

